"""
PlannerAgent - Task Planning with LLM
===================================

Uses LLM to:
1. Understand user task
2. Determine if Skill is needed
3. Generate detailed execution plan
4. Save plan to file
"""

from __future__ import annotations
import os
import logging
import asyncio
import json
from typing import Optional, List
from dataclasses import dataclass

from agents.base import BaseAgent
from agents.models import AgentConfig, AgentType, Intent

logger = logging.getLogger(__name__)


@dataclass
class Plan:
    """Execution plan generated by Planner"""
    task: str
    steps: List[str]
    skill_needed: str = None
    estimated_time: str = "unknown"
    complexity: str = "simple"  # simple or complex


class PlannerAgent:
    """
    PlannerAgent - Analyzes tasks and creates execution plans.

    Uses LLM to:
    - Understand what user wants
    - Determine if existing Skills can help
    - Create step-by-step plan
    - Save plan to file
    """

    def __init__(self, config: AgentConfig = None, shared_memory=None, ssh_manager=None):
        self.config = config or AgentConfig.default_for(AgentType.PLANNER)
        self.name = self.config.name
        self.base = BaseAgent(ssh_manager=ssh_manager)
        self.shared_memory = shared_memory
        
        # LLM config
        self._api_key = os.getenv("OMICS_LLM_API_KEY")
        self._base_url = os.getenv("OMICS_LLM_BASE_URL", "https://api.deepseek.com/v1")
        self._model = os.getenv("OMICS_LLM_MODEL", "deepseek-chat")
        
        # Available skills
        self._skills = self._load_skills()

    def _load_skills(self) -> dict:
        """Load available skills from skills directory."""
        skills = {}
        skills_dir = os.path.join(os.path.dirname(__file__), '..', 'skills')
        
        if os.path.exists(skills_dir):
            for skill_id in os.listdir(skills_dir):
                skill_path = os.path.join(skills_dir, skill_id)
                if os.path.isdir(skill_path):
                    skills[skill_id] = {
                        'id': skill_id,
                        'path': skill_path
                    }
        
        logger.info(f"Loaded {len(skills)} skills: {list(skills.keys())}")
        return skills

    async def _call_llm(self, prompt: str, system: str = None) -> str:
        """Call LLM API."""
        import aiohttp
        
        messages = []
        if system:
            messages.append({"role": "system", "content": system})
        messages.append({"role": "user", "content": prompt})
        
        payload = {
            "model": self._model,
            "messages": messages,
            "temperature": 0.3,
        }
        
        headers = {
            "Authorization": f"Bearer {self._api_key}",
            "Content-Type": "application/json"
        }
        
        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    f"{self._base_url}/chat/completions",
                    json=payload,
                    headers=headers,
                    timeout=aiohttp.ClientTimeout(total=60)
                ) as resp:
                    if resp.status != 200:
                        error = await resp.text()
                        logger.error(f"LLM API error: {resp.status} - {error}")
                        return None
                    
                    result = await resp.json()
                    return result["choices"][0]["message"]["content"]
        except Exception as e:
            logger.error(f"LLM API error: {e}")
            return None

    async def understand(self, task: str, user_id: str) -> Intent:
        """
        Understand user task and create execution plan.
        
        Returns:
            Intent with task understanding
        """
        logger.info(f"Planner: Understanding task: {task[:50]}...")
        
        # Get context (workdir, skills available)
        context = self._get_context(user_id)
        
        # Use LLM to analyze task and generate plan
        plan = await self._analyze_with_llm(task, context)
        
        # Save plan to file
        plan_path = await self._save_plan(plan, user_id)
        
        logger.info(f"Planner: Plan created - {len(plan.steps)} steps, skill={plan.skill_needed}")
        
        return Intent(
            original=task,
            is_simple_task=(plan.complexity == "simple"),
            intent_type="analysis",
            skill_needed=plan.skill_needed,
            confidence=0.8,
            suggested_steps=plan.steps
        )

    def _get_context(self, user_id: str) -> str:
        """Get context for planning."""
        parts = []
        
        # Workdir
        workdir = self.base.get_workdir(user_id)
        if workdir:
            parts.append(f"工作目录: {workdir}")
        
        # Available skills
        if self._skills:
            skill_list = ", ".join(self._skills.keys())
            parts.append(f"可用技能: {skill_list}")
        
        return "\n".join(parts) if parts else "无"

    async def _analyze_with_llm(self, task: str, context: str) -> Plan:
        """Use LLM to analyze task and generate plan."""
        
        prompt = f"""分析以下生物信息学任务，生成执行计划。

任务: {task}

环境上下文:
{context}

请以JSON格式返回执行计划：
{{
    "task": "任务描述",
    "complexity": "simple" 或 "complex",
    "skill_needed": "需要的技能(如deg_analysis, scRNA_seurat, scanpy等，无则null)",
    "steps": ["步骤1", "步骤2", ...],
    "estimated_time": "预估时间"
}}

分析原则：
- 如果任务可以用一个脚本完成 -> simple
- 如果任务需要多步骤 -> complex
- 检查可用技能，选择合适的技能辅助
- 步骤要具体可执行

只返回JSON，不要其他内容。"""

        response = await self._call_llm(prompt)
        
        if response:
            try:
                # Try to parse JSON
                data = json.loads(response)
                return Plan(
                    task=task,
                    complexity=data.get('complexity', 'simple'),
                    skill_needed=data.get('skill_needed'),
                    steps=data.get('steps', []),
                    estimated_time=data.get('estimated_time', 'unknown')
                )
            except json.JSONDecodeError:
                logger.warning(f"Failed to parse plan JSON: {response[:100]}")
        
        # Fallback - simple plan
        return Plan(
            task=task,
            complexity="simple",
            skill_needed=None,
            steps=[f"执行: {task}"],
            estimated_time="unknown"
        )

    async def _save_plan(self, plan: Plan, user_id: str) -> str:
        """Save plan to file."""
        import time
        import secrets
        
        # Create plan content
        content = f"""# CellClaw 分析计划

任务: {plan.task}
复杂度: {plan.complexity}
预估时间: {plan.estimated_time}
技能: {plan.skill_needed or '通用'}

## 执行步骤

"""
        for i, step in enumerate(plan.steps, 1):
            content += f"{i}. {step}\n"
        
        content += f"""
## 生成时间
{time.strftime('%Y-%m-%d %H:%M:%S')}
"""
        
        # Get workdir
        workdir = self.base.get_workdir(user_id) or "~/cellclaw_jobs"
        
        # Save locally first
        local_path = f"/tmp/plan_{secrets.token_hex(4)}.txt"
        os.makedirs("/tmp", exist_ok=True)
        with open(local_path, 'w') as f:
            f.write(content)
        
        logger.info(f"Plan saved to: {local_path}")
        
        return local_path

    async def create_plan(self, task: str, intent, user_id: str) -> Plan:
        """Create a full execution plan."""
        return await self._analyze_with_llm(task, self._get_context(user_id))

    def __repr__(self) -> str:
        return f"<PlannerAgent: {self.name}, skills={len(self._skills)}>"
